/*DROP TABLE USUARIO CASCADE;
DROP TABLE PASAPORTE CASCADE;
DROP TABLE DESTINO CASCADE;
DROP TABLE ELEGIR CASCADE;
DROP TABLE GUIA CASCADE;
DROP TABLE HOTEL CASCADE;
DROP TABLE SELECCIONAR CASCADE;*/

CREATE TABLE USUARIO (DNI VARCHAR (9),
		      NOMBRE VARCHAR(100),
		      APELLIDOS VARCHAR(100),
		      F_NACIMIENTO DATE,
		      EDAD NUMERIC (3),
		      EMAIL VARCHAR(50),
		      CONTRASENA VARCHAR(8) NOT NULL,
		      CONSTRAINT PK_USUARIO PRIMARY KEY (DNI),
		      CONSTRAINT CK_EDAD18 CHECK (EDAD>=18));
CREATE TABLE PASAPORTE (NUMERO VARCHAR (9),
			PAIS_EXP VARCHAR (100),
			DNI_USU VARCHAR (9),
			CONSTRAINT PK_PASAPORTE PRIMARY KEY (NUMERO),
			CONSTRAINT UK_PASAPORTE UNIQUE (DNI_USU),
			CONSTRAINT FK_PASAPORTE_USUSARIO FOREIGN KEY (DNI_USU) REFERENCES USUARIO (DNI) on delete restrict
			on update cascade);
CREATE TABLE DESTINO (PAIS VARCHAR(100),
		      CUIDAD VARCHAR(100),
		      REQ_PASS BOOLEAN NOT NULL DEFAULT TRUE,
		      PRECIOXDIA NUMERIC (10,2),
		      CONSTRAINT PK_DESTINO PRIMARY KEY (PAIS));
CREATE TABLE ELEGIR (DNI_USU VARCHAR (9),
		       PAIS_DEST VARCHAR(100),
		       PRECIO NUMERIC(10,2),
		       F_IDA DATE,
		       F_VUELTA DATE,
		       CONSTRAINT PK_ELEGIR PRIMARY KEY (DNI_USU, PAIS_DEST),
		       CONSTRAINT FK_ELEGIR_USUARIO FOREIGN KEY (DNI_USU) REFERENCES USUARIO (DNI),
		       CONSTRAINT FK_ELEGIR_DESTINO FOREIGN KEY (PAIS_DEST) REFERENCES DESTINO (PAIS));
CREATE TYPE ESPECIALIDAD_ENU AS ENUM ('Geografía',
				      'Historia',
				      'Arquitectura',
				      'Comida');
CREATE TABLE GUIA (ID SERIAL,
		    DNI VARCHAR(9),
		    NOMBRE VARCHAR(100),
		    APELLIDOS VARCHAR(100),
		    ESPECIALIDAD ESPECIALIDAD_ENU NOT NULL,
		    PAIS_DEST VARCHAR(100),
		    CONSTRAINT PK_GUIAS PRIMARY KEY (ID),
		    CONSTRAINT UK_GUIAS UNIQUE (DNI),
		    CONSTRAINT FK_GUIAS_DESTINO FOREIGN KEY (PAIS_DEST) REFERENCES DESTINO (PAIS));
CREATE TYPE ESTRELLAS_ENU AS ENUM ('1', '2','3','4','5');
CREATE TABLE HOTEL(COD SERIAL,
		   NOMBRE VARCHAR(100),
		   ESTRELLAS ESTRELLAS_ENU NOT NULL,
		   DIRECCION VARCHAR (200),
		   WIFI BOOLEAN DEFAULT TRUE,
		   PARKING BOOLEAN DEFAULT FALSE,
		   PAIS_DEST VARCHAR (100),
		   PRECIOXNOCHE NUMERIC (10,2),
		   CONSTRAINT PK_HOTEL PRIMARY KEY (COD),
		   CONSTRAINT UK_HOTEL UNIQUE (NOMBRE),
		   CONSTRAINT FK_HOTEL_DESTINO FOREIGN KEY (PAIS_DEST) REFERENCES DESTINO (PAIS));
CREATE TABLE RESERVAR (DNI_USU VARCHAR (9),
			  PAIS_DEST VARCHAR (100),
			  COD_HOTEL SERIAL,
			  PRECIO_H NUMERIC (10,2),
			  F_ENTRADA DATE,
			  F_SALIDA DATE,
			  CONSTRAINT PK_RESERVAR PRIMARY KEY (DNI_USU, PAIS_DEST, COD_HOTEL),
			  CONSTRAINT FK_RESERVAR_ELEGIR FOREIGN KEY (DNI_USU, PAIS_DEST) REFERENCES ELEGIR (DNI_USU, PAIS_DEST),
			  CONSTRAINT FK_RESERVAR_HOTEL FOREIGN KEY (COD_HOTEL) REFERENCES HOTEL (COD));

